/**
 * File templates for newly created game projects. OpenGenie scaffolds a
 * minimal-but-runnable Godot 4 project so the Run button works immediately
 * and the AI assistant has a valid starting point to build on.
 */

/**
 * Project names are interpolated into Godot config strings, GDScript string
 * literals and Markdown. In those contexts `"` delimits the string, `\` is
 * an escape character, and a raw newline breaks out of the value entirely —
 * e.g. a name containing "\n[autoload]\n…" would inject a config section
 * into project.godot that executes arbitrary GDScript when the project runs.
 * Names are display-only, so strip the dangerous characters rather than
 * trying to escape them per-context.
 */
function sanitize(name: string): string {
  return (
    name
      .replace(/[\\\u0000-\u001f\u007f]/g, ' ')
      .replace(/"/g, "'")
      .replace(/\s+/g, ' ')
      .trim() || 'Untitled Game'
  )
}

export function projectGodot(name: string): string {
  return `; Engine configuration file.
; Generated by OpenGenie — edits are welcome, Godot also rewrites this file.
config_version=5

[application]

; No engine splash — the game boots straight into its first scene on black.
boot_splash/bg_color=Color(0, 0, 0, 1)
boot_splash/show_image=false
config/name="${sanitize(name)}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.7")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1152
window/size/viewport_height=648
; canvas_items stretch keeps the game readable at any size — important for
; OpenGenie's embedded game view, which can be resized freely.
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
; Required for macOS/mobile exports (arm64 needs ETC2/ASTC texture import).
textures/vram_compression/import_etc2_astc=true
`
}

export function mainTscn(name: string): string {
  return `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="Title" type="Label" parent="."]
offset_left = 40.0
offset_top = 40.0
offset_right = 800.0
offset_bottom = 90.0
text = "${sanitize(name)} — built with OpenGenie. Ask the assistant to make a game!"
`
}

export function mainGd(name: string): string {
  // GDScript uses tab indentation by convention (Godot's default).
  // The opengenie header block matches the format mandated in agentsMd() —
  // the scaffold must itself comply so the AI sees a live example (and so a
  // future UI parser finds a header in every file, including this one).
  return [
    '#=== opengenie ===',
    '# kind: other',
    '# name: Main',
    '# summary: Entry scene script — instantiates entities and hosts the systems.',
    '# uses: none',
    '#=== /opengenie ===',
    'extends Node2D',
    '',
    '',
    'func _ready() -> void:',
    `\tprint("${sanitize(name)} is running — built with OpenGenie")`,
    ''
  ].join('\n')
}

export function iconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="28" fill="#7c5cff"/><path d="M52 40l34 24-34 24z" fill="#fff"/></svg>
`
}

export function gitignore(): string {
  return `# Godot 4 cache/imported data
.godot/
.DS_Store

# OpenGenie run helpers (auto-generated while the game runs, removed on stop)
override.cfg
opengenie_test_agent.gd

# OpenGenie export output
exports/

# OpenGenie local state (chat history, attachments, test screenshots)
.opengenie/
`
}

/**
 * AGENTS.md is picked up automatically by OpenCode (and other coding agents),
 * so freshly created games come with the context the AI needs to work well.
 *
 * The "File headers" section below is load-bearing: it defines the exact
 * comment-block format ("#=== opengenie ===" … keys … "#=== /opengenie ===")
 * that a future OpenGenie UI feature will parse to display the project's
 * structure. Change the format here and that parser in lockstep.
 */
export function agentsMd(name: string): string {
  return `# ${sanitize(name)}

This is a **Godot 4** game project created with **OpenGenie**, an AI-powered game engine.

## Scope — you build Godot games, nothing else

OpenGenie creates video games with the Godot engine; that is the ONLY thing you can
build. When a request falls outside that, push back honestly instead of attempting it:

- **Not a game at all** (a website, web app, mobile app, chatbot, script, ...): say
  plainly that OpenGenie only makes games and you can't build that here.
- **A game aimed at another platform or engine** (a WeChat mini-game, a Roblox
  experience, a Unity/Unreal project, ...): offer to build the same game in Godot
  instead — the gameplay they want almost always translates.

Never assume the user knows what Godot is. When it comes up, introduce it in a sentence
or two of plain language: Godot is a free, open-source game engine behind thousands of
shipped commercial games; it handles both 2D and 3D, and a single project exports to
Windows, macOS, Linux, phones, and the web. Then move the conversation forward to what
their game should be, and build it.

## Ground rules

- The playable entry scene is \`main.tscn\` (configured as \`run/main_scene\`); its script is \`main.gd\`.
- Write game logic in GDScript. Use tabs for indentation (Godot's default).
- Keep \`run/main_scene\` in \`project.godot\` pointing at the scene the player should start in.
- The user runs the game through OpenGenie's Run button, which runs the full native engine
  embedded in the app — the project must always launch cleanly and without script errors.
- For art, prefer simple generated assets (SVG/PNG) committed to the repository.
- You have \`websearch\` and \`webfetch\` tools — use them to look up Godot 4 APIs, GDScript
  idioms, or game-design references when you're unsure, instead of guessing.
- Need a scratch file? Use the system temp directory. The user's personal folders
  (Desktop, Documents outside this project, Downloads, Photos, cloud drives) are
  off-limits and blocked — never try to read or write them.

## Your image-enabled subagents

Your own model may not accept image input, so two subagents (invoked through the task
tool) do the looking for you — both run a model that can see:

- **image-reader** — describes image files in detail. Hand it file path(s) plus the
  specific questions you need answered.
- **game-tester** — plays the game off-screen with the opengenie tools and checks the
  screenshots it takes. Tell it what changed and what to verify; it reports back.

If your model does view images directly, the subagents are optional for reading but
game-tester is still the cheapest way to run a full verification pass.

## Reference screenshots & images

Users attach screenshots and reference images (games they like, sketches, mock-ups) to
their messages. Each attached image is also saved under \`.opengenie/attachments/\` and
its path listed in the message — if you cannot view images yourself, send those paths to
the **image-reader** subagent and ask for everything you'll need (art style, palette,
layout, mechanics, exact text) before you start building; its answer is your only view
of the image.

An attached image is a design brief — study it closely before writing code or generating
art, and keep referring back to it:

- **Art**: match the image's art style, color palette, proportions, lighting, and mood in
  every asset you create. Put those specifics into your generation prompts (e.g. "16-bit
  pixel art, dusk palette of deep purples and orange highlights, chunky outlines") rather
  than generic descriptions.
- **Game logic**: read the genre, camera perspective, controls, HUD layout, and visible
  mechanics out of the screenshot and build those — don't substitute a generic version of
  the genre.
- When the goal is "make it look like this", verify it does: have the **game-tester**
  subagent screenshot the running game and compare it against the reference before
  reporting back.

## Architecture — Entity Component System (required)

Structure ALL game code as ECS, mapped onto Godot like this:

- **Components — \`components/c_*.gd\`** — pure data. Extends \`Node\`; \`@export\` data
  fields, signals, and trivial accessors only — no game logic. In \`_ready\` the component
  adds itself to a group named after its file (\`c_health.gd\` → group \`"c_health"\`) so
  systems can find it.
- **Entities — \`entities/e_*.tscn\` (with an \`entities/e_*.gd\` script)** — scenes that
  compose components as child nodes. An entity script only wires its own components
  together; behavior belongs in systems.
- **Systems — \`systems/s_*.gd\`** — all game logic. Extends \`Node\`, attached under the
  main scene (or an autoload); each frame it processes the members of the component groups
  it cares about (\`get_tree().get_nodes_in_group("c_...")\`).

Rules:

- Every gameplay feature = component(s) for its data + a system for its behavior + entities
  composed from components. Never put gameplay logic in an entity or component script.
- Use exactly the \`e_\`, \`c_\`, \`s_\` file prefixes, each kind in its folder (create the
  folders on first use). Non-ECS code (menus, HUD, math helpers, shaders) lives outside
  those three folders — e.g. \`ui/\` or \`util/\`.
- \`main.tscn\` stays the entry scene: it instantiates entities and hosts the systems.

## Art & 3D assets

**Art comes first.** The FIRST playable version of a game must already look good — never
deliver a gray-box build of bare rectangles and default labels. Create the art a feature
needs (player, enemies, items, background, UI) before or alongside its gameplay code, and
build the scenes with those assets from the start. Use the generation tools below when
they're available; when they're not, craft the art yourself (SVG/PNG sprites, styled
Godot primitives) — missing tools are not a reason to ship an empty-looking game.

All art lives under \`assets/\`, in sub-folders that mirror the ECS structure — an asset
sits under the same category as the code that owns it:

- \`assets/entities/<entity-id>/\` — art for one entity (e.g. \`assets/entities/e_player/\`).
- \`assets/ui/\` — HUD icons, menu art, fonts.
- \`assets/shared/\` — pieces several entities reuse (tilesets, common materials, props).

Keep this layout for ALL assets, hand-made or generated. Never scatter art in the
project root or next to scripts.

### Generating 2D art (\`generate_2d_asset\`)

If the \`generate_2d_asset\` tool is available (server \`opengenie\` — the user enables it
by adding an OpenAI API key in the AI settings panel), you can generate 2D art:

- Output is fixed: one 1024×1024 PNG with a TRANSPARENT background, medium quality —
  ideal for sprites, icons, items and UI elements. Godot auto-imports it as a texture.
- One subject per call. Prompt like an artist brief: subject, colors/materials, art
  style, and the view angle the game needs (e.g. "side view, pixel-art style" for a
  platformer sprite, "top-down" for a shooter, "flat vector icon" for UI).
- \`folder\` + \`name\` decide where it lands, mirroring the ECS layout exactly like 3D
  assets: \`folder: "entities/e_player", name: "player-sprite"\`
  → \`assets/entities/e_player/player-sprite/\`.

### Generating 3D models (\`generate_3d_asset\`)

If the \`generate_3d_asset\` tool is available (server \`opengenie\` — the user enables it
by adding Tencent HY 3D credentials in the AI settings panel), you can generate real,
textured 3D models:

- One object per call. Prompt like an artist brief: subject, shape, colors/materials,
  style — e.g. "a small red rocket ship, rounded retro style, glossy paint, cartoon".
- \`folder\` + \`name\` decide where it lands: \`folder: "entities/e_player", name: "rocket"\`
  → \`assets/entities/e_player/rocket/\`. Match the folder to the owning ECS file.
- Keep \`face_count\` modest (default 60000) — this is a game, not a render farm. Use
  \`generate_type: "LowPoly"\` for stylized games and \`"Geometry"\` for untextured shapes.
- Calls take 1–5 minutes and return a preview image — LOOK at it (via the image-reader
  subagent if you can't view images); if the model is wrong, refine the prompt and
  regenerate rather than shipping a bad asset.
- Godot auto-imports the saved \`.obj\`/\`.glb\` under \`res://\` — instance it in the
  entity's scene.

### Asset previews & user feedback

Every generated asset's preview is shown to the user in the chat with a "Request
changes" button. When the user gives feedback on an asset (e.g. 'Change the
"rocket" asset (assets/entities/e_player/rocket): make it blue'):

- Regenerate with the SAME \`folder\` and \`name\` so the new files replace the old ones —
  scenes referencing the asset keep working. Never create "-v2" copies.
- Fold the feedback into a full, self-contained prompt (the generator has no memory of
  the previous attempt — re-describe the whole asset, not just the delta).
- Check the returned preview against the user's feedback before reporting back (ask the
  image-reader subagent to describe the generated file if you can't view images).

If a generation tool is NOT available, don't ask the user for it or fake a call — build
placeholder art instead (SVG/PNG sprites, Godot primitive meshes), organized in the same
\`assets/\` layout.

## File headers (required — OpenGenie parses these)

Start EVERY code file you create or edit with this comment block, before anything else
(before \`extends\`). OpenGenie parses it mechanically to show the project's structure in
the UI, so the format is exact: same keys, same order, one \`key: value\` per line, using
the file type's line-comment prefix (\`#\` in GDScript, \`//\` in shaders).

Example for \`components/c_health.gd\`:

\`\`\`gdscript
#=== opengenie ===
# kind: component
# name: Health
# summary: Hit points with a died signal emitted when hp reaches 0.
# uses: none
#=== /opengenie ===
\`\`\`

- \`kind\` — one of \`entity | component | system | autoload | ui | util | shader | other\`.
- \`name\` — short display name in PascalCase words.
- \`summary\` — one line, plain language, under 120 characters; shown to the user in the UI.
- \`uses\` — comma-separated \`c_*\` component files this file composes (entities) or
  queries (systems); \`none\` if none.
- Keep the header up to date whenever the file's purpose changes; never reorder, rename,
  or reformat the keys.
- Scene files (.tscn) cannot hold comments — the entity's \`e_*.gd\` script header covers
  the entity.

## Testing your work

Delegate gameplay verification to the **game-tester** subagent (task tool): it launches
the game off-screen, drives it with input, inspects state and logs, and — unlike you,
possibly — actually sees the screenshots it takes. Tell it what changed and exactly what
to verify; it reports what works and what's broken, and you fix and re-test.

You also have the same MCP tools (server \`opengenie\`) yourself — fine for quick
text-only probes without a full test pass (but leave screenshot judgment to game-tester
unless your model views images):

1. \`run_game_test\` — starts the game off-screen (full engine, real rendering).
2. \`game_scene_tree\` — discover node paths; \`game_state\` — evaluate a GDScript expression
   (e.g. \`get_node("/root/Main/Score").text\`) to assert state.
3. \`game_input\` — send scripted keys/mouse (DOM-style key names like "ArrowLeft", "Space").
4. \`game_screenshot\` — capture a PNG of the running game. It returns the image AND saves
   it inside the project at \`.opengenie/test-shots/\`; if you can't view images, hand that
   in-project path to **image-reader** — never copy screenshots or look for them anywhere
   else. \`game_logs\` — read the game's console output (prints and script errors). It also
   includes output from the **user's own play sessions** — when the user reports a bug or
   crash, call \`game_logs\` first to see what actually happened.
5. \`stop_game_test\` — always stop the run when you're finished.

### When to test — use judgment, testing takes real time

**Do test** after changes that are large or gameplay-critical:
- New mechanics or systems (movement, collision, scoring, spawning, win/lose, save/load).
- Refactors that touch several functions or scenes, or change the scene structure.
- Changes to input handling, the main loop, or anything that could break launch.
- When several smaller untested edits have accumulated — rule of thumb: after ~3 small edits
  without a test run, or before telling the user a feature is complete.

**Don't test** after trivial edits: tuning a single constant, colors/text/labels, comments, or
renames with no behavior change. Just mention that the change was too small to warrant a test run.

### How to test — keep it cheap and targeted

- Test what changed, not everything. Give game-tester a focused brief: which mechanic you
  touched, the controls that exercise it, and the expected outcome. (Doing it yourself:
  run → \`game_logs\` → probe the mechanic via \`game_state\` → a few \`game_input\` actions →
  \`game_logs\` again → \`stop_game_test\`.)
- Each test run has a hard budget (~40 game tool calls / 8 minutes) before the tools shut
  off — an open-ended brief like "verify everything" will burn it before concluding. Ask
  for a handful of specific checks; split genuinely broad verification into separate runs.
- If script errors turn up at any point, fix them and re-run the test before reporting.
- Save full regression passes (controls + scoring + game over + restart) for major milestones.
- Always report what you verified — or that you deliberately skipped testing and why.

### Performance — \`.opengenie/perf.log\`

While the game runs (the user playing OR a test run), OpenGenie measures every frame and
logs frame-rate stats per 60-second window: \`avg\`, \`min\`, \`max\`, \`1%low\`, \`0.1%low\`
(all in FPS; the lows are the FPS equivalent of the average frame time of the slowest 1% /
0.1% of frames — the standard stutter metrics). The lines appear in \`game_logs\` as they
are produced, and the persistent history lives in \`.opengenie/perf.log\`.

When the user reports lag, stutter, or slowness: read \`.opengenie/perf.log\` FIRST — it
holds real measurements from their own play sessions. A low \`avg\` means sustained load
(too much per-frame work); a good \`avg\` with bad \`1%low\`/\`0.1%low\` means hitches
(spikes from allocations, node spawning, loading in \`_process\`, etc.). After optimizing,
run the game again and compare new windows against the old ones.
`
}
