/**
 * File templates for newly created game projects. OpenGenie scaffolds a
 * minimal-but-runnable Godot 4 project so the Run button works immediately
 * and the AI assistant has a valid starting point to build on.
 */

/**
 * Project names are interpolated into Godot config strings, GDScript string
 * literals and Markdown. In those contexts `"` delimits the string, `\` is
 * an escape character, and a raw newline breaks out of the value entirely —
 * e.g. a name containing "\n[autoload]\n…" would inject a config section
 * into project.godot that executes arbitrary GDScript when the project runs.
 * Names are display-only, so strip the dangerous characters rather than
 * trying to escape them per-context.
 */
function sanitize(name: string): string {
  return (
    name
      .replace(/[\\\u0000-\u001f\u007f]/g, ' ')
      .replace(/"/g, "'")
      .replace(/\s+/g, ' ')
      .trim() || 'Untitled Game'
  )
}

export function projectGodot(name: string): string {
  return `; Engine configuration file.
; Generated by OpenGenie — edits are welcome, Godot also rewrites this file.
config_version=5

[application]

config/name="${sanitize(name)}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.7")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1152
window/size/viewport_height=648
; canvas_items stretch keeps the game readable at any size — important for
; OpenGenie's embedded game view, which can be resized freely.
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
; Required for macOS/mobile exports (arm64 needs ETC2/ASTC texture import).
textures/vram_compression/import_etc2_astc=true
`
}

export function mainTscn(name: string): string {
  return `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="Title" type="Label" parent="."]
offset_left = 40.0
offset_top = 40.0
offset_right = 800.0
offset_bottom = 90.0
text = "${sanitize(name)} — built with OpenGenie. Ask the assistant to make a game!"
`
}

export function mainGd(name: string): string {
  // GDScript uses tab indentation by convention (Godot's default).
  return [
    'extends Node2D',
    '',
    '',
    'func _ready() -> void:',
    `\tprint("${sanitize(name)} is running — built with OpenGenie")`,
    ''
  ].join('\n')
}

export function iconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="28" fill="#7c5cff"/><path d="M52 40l34 24-34 24z" fill="#fff"/></svg>
`
}

export function gitignore(): string {
  return `# Godot 4 cache/imported data
.godot/
.DS_Store

# OpenGenie AI test-run helpers (auto-generated at test start, removed on stop)
override.cfg
opengenie_test_agent.gd

# OpenGenie export output
exports/
`
}

/**
 * AGENTS.md is picked up automatically by OpenCode (and other coding agents),
 * so freshly created games come with the context the AI needs to work well.
 */
export function agentsMd(name: string): string {
  return `# ${sanitize(name)}

This is a **Godot 4** game project created with **OpenGenie**, an AI-powered game engine.

## Ground rules

- The playable entry scene is \`main.tscn\` (configured as \`run/main_scene\`); its script is \`main.gd\`.
- Write game logic in GDScript. Use tabs for indentation (Godot's default).
- Keep \`run/main_scene\` in \`project.godot\` pointing at the scene the player should start in.
- The user runs the game through OpenGenie's Run button, which runs the full native engine
  embedded in the app — the project must always launch cleanly and without script errors.
- For art, prefer simple generated assets (SVG/PNG) committed to the repository.

## Testing your work

You have MCP tools (server \`opengenie\`) to run and verify the game yourself:

1. \`run_game_test\` — starts the game off-screen (full engine, real rendering).
2. \`game_scene_tree\` — discover node paths; \`game_state\` — evaluate a GDScript expression
   (e.g. \`get_node("/root/Main/Score").text\`) to assert state.
3. \`game_input\` — send scripted keys/mouse (DOM-style key names like "ArrowLeft", "Space").
4. \`game_screenshot\` — capture a PNG of the running game; \`game_logs\` — read the game's
   console output (prints and script errors). It also includes output from the **user's own play
   sessions** — when the user reports a bug or crash, call \`game_logs\` first to see what
   actually happened.
5. \`stop_game_test\` — always stop the run when you're finished.

### When to test — use judgment, testing takes real time

**Do test** after changes that are large or gameplay-critical:
- New mechanics or systems (movement, collision, scoring, spawning, win/lose, save/load).
- Refactors that touch several functions or scenes, or change the scene structure.
- Changes to input handling, the main loop, or anything that could break launch.
- When several smaller untested edits have accumulated — rule of thumb: after ~3 small edits
  without a test run, or before telling the user a feature is complete.

**Don't test** after trivial edits: tuning a single constant, colors/text/labels, comments, or
renames with no behavior change. Just mention that the change was too small to warrant a test run.

### How to test — keep it cheap and targeted

- Test what changed, not everything: run → \`game_logs\` (no script errors) → probe the specific
  mechanic you touched (\`game_state\` or a screenshot) → a few \`game_input\` actions that exercise
  it → check \`game_logs\` again for new errors → \`stop_game_test\`.
- If \`game_logs\` shows script errors at any point, fix them and re-run the test before reporting.
- Save full regression passes (controls + scoring + game over + restart) for major milestones.
- Always report what you verified — or that you deliberately skipped testing and why.
`
}
